name: task-manager

on: 
  push:
    branches:
      - master      

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
                
    - name: Dependencies
      run: npm install
    
    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/pm-web
